### ISSUE TITLE
How to use dust-view-engine ?

### ISSUE THREAD

**Issue by RameshRM** [raptorjs/view-engine-dust#1]
I have setup the view engine and load the template 

``` code
viewEngine.register('dust', require('view-engine-dust'), {
    dust: dust
});

            var templateFile = require.resolve('./hello-world.dust');
            var template = viewEngine.load(templateFile);
template.render({}, res);

```

Template.errors() on view-engine-dust module "  Uncaught ReferenceError: dust is not defined"

**Comment by patrick-steele-idem** [comment]
The following should work:

``` javascript
var dust = require('dustjs-linkedin');

viewEngine.register('dust', require('view-engine-dust'), {
    dust: dust
});
```

**Comment by RameshRM** [comment]
Nope, seeing errors `dust is not defined`

**Comment by patrick-steele-idem** [comment]
What is the stack trace?

**Comment by RameshRM** [comment]
```
/Users/ramahadevan/github.paypal.com/test-dust-viewengine/hello-world.dust.js:1
e),ctx,"h").w("!</body></html>");}body_0.__dustBody=!0;return body_0;})(dust);
ReferenceError: dust is not defined
    at Object.<anonymous> (/Users/ramahadevan/github.paypal.com/test-dust-viewengine/hello-world.dust.js:1:257)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports.fs.stat.inFileLastModified (/node_modules/view-engine-dust/lib/onLoad.js:47:49)
    at Object.oncomplete (fs.js:107:15)
```

**Comment by patrick-steele-idem** [comment]
Dust stack traces are pretty bad. I will need more context.

**Comment by patrick-steele-idem** [comment]
I have a test for Dust in the main `view-engine` project:
https://github.com/raptorjs/view-engine/blob/3c7fccc613d15688092156407abf16e6e83e6c27/test/test.js#L145-L172

What are you doing differently?

**Comment by RameshRM** [comment]
#### Running the simple express/ or running the renderDustTemplate() , either one throws exception ,

``` javascript
'use strict';
var express = require('express');
var http = require('http');
var viewEngine = require('view-engine');

viewEngine.configure({
    engines: {
        'view-engine-dust': {
            extensions: ['dust']
        }
    }
});

var app;
var port = 3000;
var server;

function startServer() {
    app = express();
    server = http.createServer(app);
    server.on('listening', function() {
        console.log('Listening on port ' + port);
    });
    server.listen(port);
    app.get('/simple', function(req, res) {
        var templateFile = require.resolve('./hello-world.dust');
        var template = viewEngine.load(templateFile);
        template.render({}, res);
    });

}

function renderDustTemplate() {
    var templateFile = require.resolve('./hello-world.dust');
    var template = viewEngine.load(templateFile);
    template.render({}, function(err, result) {
        console.log(result);
    });
}

startServer();
```

**Comment by RameshRM** [comment]
I know whats happening, the compiled DustJS seem to be the issue, wrapping the dust to the function seem like the issue
